### ISSUE TITLE
Viability

### ISSUE THREAD

**Issue by Rasgnarok** [trentech/ProjectBorders#1]
Hey Tren! Wasn't sure where to ask this, but will this project be continued somewhere? I am currently on spongeforge 1683, Minecraft 1.10.2 - and I would have need for the chunk-generating functions that this offers.

Do you have plans on pursuing this, or are you merging it? If so, will it be available for 1.10.2 soon?

Thanks in advance!

**Comment by trentech** [comment]
I will be continuing this plugin. I'm just procrastinating on setting up a dedicated thread on Sponge Forums. I just tested the chunk generator last night. Seems to be working better on latest bleeding builds.

**Comment by Rasgnarok** [comment]
That's actually a great relief. Because I am having incredible issues with chunk loading, and nothing is really compatible with the latest forge/spongeforge I got.

**Comment by trentech** [comment]
https://forums.spongepowered.org/t/project-borders-v0-1-1/14412
